// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePanelContentAsJson(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Run(arg1:string):Promise<string>;

export function SetCurrentItemIndex(arg1:number,arg2:number):Promise<void>;

export function UpdateContent(arg1:number):Promise<void>;
