// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function GetFilePanelContentAsJson(arg1) {
  return window['go']['main']['App']['GetFilePanelContentAsJson'](arg1);
}

export function GoBack(arg1) {
  return window['go']['main']['App']['GoBack'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MainAction(arg1) {
  return window['go']['main']['App']['MainAction'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SetCurrentItemIndex(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentItemIndex'](arg1, arg2);
}

export function UpdateContent(arg1) {
  return window['go']['main']['App']['UpdateContent'](arg1);
}
